apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-backend.fullname" . }}
  labels:
    app: {{ include "demo-backend.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "demo-backend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "demo-backend.name" . }}
    spec:
      containers:
        - name: demo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources: {{ toYaml .Values.resources | nindent 10 }}
