apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "angular-frontend.fullname" . }}
  labels:
    app: {{ include "angular-frontend.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "angular-frontend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "angular-frontend.name" . }}
    spec:
      containers:
        - name: angular
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources: {{ toYaml .Values.resources | nindent 10 }}
